[#install]
== Build and install FastScapeLib

**FastScapeLib** is not yet available as a binary package, so you need
to build and install it manually.

=== Download the source files

First, download the sources using git:

----
git clone https://github.com/fastscape-lem/fastscapelib-fortran
----

Alternatively, you can visit the URL of the source repository
(https://github.com/fastscape-lem/fastscapelib-fortran) and download
the source files as an archive (see the "clone or download button").

=== Requirements

To build FastScapelib, you need a Fortran compiler (e.g., `gfortran`,
part of GCC) and CMake (https://cmake.org/). Both can easily be
installed on major platforms, e.g., using Homebrew on MacOS or apt-get
on Linux/Debian. GCC compilers are also available for Windows platforms
(see http://www.mingw.org/).

=== Build using CMake

Run the following commands from the source directory to build the
**FastScapeLib** Fortran library:

----
mkdir build
cd build
cmake <options> ..
make
----

There are several build options, here shown with their default values:

- `-DBUILD_FASTSCAPELIB_STATIC=ON`: build fastscapelib as a static library
- `-DBUILD_FASTSCAPELIB_SHARED=OFF`: build fastscapelib as a shared library
- `-DUSE_FLEXURE=OFF`: include flexure routines in the library
- `-DBUILD_EXAMPLES=OFF`: "build usage examples that are in the 'examples' directory

=== Install the Fortran library

If you want to install the **FastScapeLib** Fortran static/shared
libraries in your system, then simply run:

----
make install
----

You should now be able to link your programs using **FastScapeLib**
routines, e.g., with `-lfastscapelib_fortran`. See some Fortran programs
in the 'examples' folder.

=== Install the Python package (using conda)

[NOTE]
====
If you want to use this tool from within Python, you may consider using the
**FastScape** package instead, which is built on top of FastScapeLib and which
provides a high-level, user-friendly interface. See
https://fastscape.readthedocs.io.
====

**FastScapeLib**'s Python bindings are available as a conda package
(https://docs.conda.io/en/latest/). Conda can be installed from
https://docs.conda.io/en/latest/miniconda.html.

Then run the following command:

----
conda install fastscapelib-f2py -c conda-forge
----

You should now be able to import the package from within Python, e.g.,

----
>>> import fastscapelib_fortran as fs
----

There is a Jupyter notebook in the 'examples' folder showing simple
usage of the library.

=== Install the Python package (from source)

You can also install **FastScapeLib**'s Python bindings from source, e.g, for
development purpose. Run the following command from the source directory (i.e.,
the top-level folder containing the file `setup.py`):

----
python -m pip install .
----

This will also temporarily install all the tools needed to build the package
(except a Fortran compiler, which must be already installed). Note: you need pip
>= 10.

If you experience issues when installing or importing the package (NumPy
compatibility issues), try running pip without build isolation:

----
python -m pip install . --no-build-isolation
----

Note that in this case you may first need to manually install all the tools
required to build the package (i.e., CMake, NumPy, scikit-build).
