name: test-doc

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'

jobs:
  adoc-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build docs
      uses: avattathil/asciidoctor-action@v2
      with:
          program: "asciidoctor docs/index.adoc -o docs/index.html"
